# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: AutoBuild

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: 'Checkout 代码'
        uses: actions/checkout@v2

      - name: '使用 Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: '安装依赖'
        run: npm install

      - name: '构建静态文件'
        run: npm run build

      - name: '打包可执行文件'
        run: npm run make

      - name: '上传 artifact'
        uses: actions/upload-artifact@v3
        with:
          name: blurlyric-${{ matrix.os }}
          path: blurlyric-${{ matrix.os }}-x64