# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: AutoBuild

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x]

    steps:
      - name: 'Checkout 代码'
        uses: actions/checkout@v2

      - name: '使用 Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: '安装依赖'
        run: npm install

      - name: '构建静态文件'
        run: npm run build

      - name: '打包可执行文件'
        run: npm run make

      - name: '上传macOS artifact'
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: blurlyric-macos
          path: dist_electron/*-universal.dmg

      - name: '上传Windows artifact'
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: blurlyric-windows
          path: out\make\squirrel.windows\x64\blurlyric-2.2.0-x64.zip
      - name: '上传Ubuntu artifact'
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: blurlyric-ubuntu
          path: dist_electron/*.AppImage