# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: autoBuild

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: '使用 Node.js ${{ matrix.node-version }}'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: '安装依赖'
      run: npm install
    - run: npx electron-forge import

    - name: '构建静态文件'
      run: npm run build
    - name: '打包可执行文件'
      run: npm run make
    
    - name: '打包zip'
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'blurlyric-win32-x64.zip'
        directory: 'D:\a\BlurLyric2.0\BlurLyric2.0\out\blurlyric-win32-x64'
        path: '../../'


    - name: '创建Release'
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          由机器人自动构建
          若有报错请上报issue
        draft: false
        prerelease: false
        
    - name: '将构建文件上传至release-asset'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 'D:\a\BlurLyric2.0\BlurLyric2.0\blurlyric-win32-x64.zip'
        asset_name: blurlyric-win32-x64.zip
        asset_content_type: application/zip